### PR TITLE
 dynamic criteria through maps and added DateInYear and DateNotInYear,  added page and pagesize clause and made 10 the default to take

### PR DESCRIPTION
**Pull request by nfdevil**
Hi,

I've got an opinionated fork. If you like a part of it, you could merge it.

Opinions:
- Serilog as the logger
- xunit and FluentAssertions for testing
- require 'this' qualifier for properties, fields, events, ...
- var usage in declarations

I'm going to add more functionality to it, alot more criterias for example.

Kr,
Appsum Solutions

### CODE REVIEW

**Comment by trenoncourt** [comment]
Hi,

Thanks for your contribution.

Why not for all your opinions but this qualifier, i'm using rider/resharper and it tells that this is à redondant qualifier.

For var, i'm using it when the right type is obvious, but why not.

Anyway ~~i wish we could work together~~  we need to work together :wink:

**Comment by trenoncourt** [comment]
In 2.0 i want to have DI to, but maybe it means that AQ would only be compatible with aspnet core?

**Comment by nfdevil** [comment]
I'm indeed using Resharper too, but I've set some settings according to 'best practices' I've found over the years I'm working in C#. The 'this' keyword helps me to show that I'm using the current object's property. 
The var keyword types faster imo :)
The DI, indeed, it could give problems for .NET Framework. We've gotta look into this before just changing it.

**Comment by nfdevil** [comment]
However, for the DI, any good project uses DI, even if it is built with .NETFx. If the readme states that it's required to use a DI container (chosen by the user) and configure it to have the AQ as a Lifetime dependency, this should not cause a problem imo.

**Comment by trenoncourt** [comment]
Hi @nfdevil,

I'll accept this contribution, thanks for your help.
Serilog, xunit & fluentassertions are very good choice.

For this & var keyword i use the same guidelines as Microsoft for aspnet core:
this: only when needed
var: only when type is obvious
See this file for example: [https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs)

But why not use this & var everywhere if you need that.

I see 1 breaking change with older versions :
= is now ==
And one feature change with older versions :
default to take is 10

Maybe we could allow = and == to remove breaking ?

Thanks,
Thibaut

**Comment by trenoncourt** [comment]
@nfdevil,
1.7.0 is out with your changes 🎉 

Your DateInYear filter make me think about a new feature in AQ : 
**modifiers**
Modifiers are functions that take input and send output and then we can apply with other closes.

modifiers ❤️ filters
for example juste with one DateInYear modifier you can use all filters:
`mydate:year=1989` `mydate:year!=1989` `mydate:yearContains=9` `mydate:year>9` ...

modifiers ❤️ select
for example juste with one DateInYear modifier you can use all filters:
`select=name:uppercase,color:stringtohex,amount:percent`

In a future release, modifiers could be chained too like that:
`mydate:year:last(2)=89` to take only last 2 digits of year

Here is my discord if you want to talk about it : `trenoncourt#2280`

**Pull request merged**
