### PR TITLE
 capability to include navigation properties on multiple levels

### PR DESCRIPTION
**Pull request by nurhat**
first try, we may need find a better way:)

### CODE REVIEW

**Comment by trenoncourt** [comment]
@nurhat, thanks for your help.
Do you want to be part of project collaborators ?

**Comment by nurhat** [comment]
@trenoncourt , you are welcome. Please add me to the project collaborators.

**Comment by trenoncourt** [comment]
@nurhat done! 
I'm trying to add a selectmany version because when you select only one value eg: /products?select=SalesOrderDetail.Product.ProductId, you want to only get an array of productId but you'll get array of array.
So i have added selectmany clause in select-many branch but for now it only works with this test : /products?selectmany=SalesOrderDetail.Product. you get an array of product as wanted.
We can discuss about it throught gitter autoqueryable lobby if you want.

**Comment by nurhat** [comment]
@trenoncourt , yes that is why i told "first try".  Actually, the future will be useful when we can create queries to select only desired properties of collections, and provide automatic dto projection . The automatic dto projection should also be available when selecting single properties.

e.q select=SalesOrderDetail.Product.ProductId, SalesOrderDetail.LineTotal,SalesOrderDetail.Product should create following json result;
 ```
 {
  "SalesOrderDetail": [
    {
      "ProductId": 1,
      "LineTotal": 1,
      "Product": {
        "Name": "1",
        "ProductId": "1"
      }
    },
    {
      "ProductId": 1,
      "LineTotal": 2,
      "Product": {
        "Name": "1",
        "ProductId": "1"
      }
    }
  ]
}
```
eq. select =name,productcategory.name  should create following json result

```
{
  "Product": [
    {
      "Name": "x", 
      "ProductCategory": {
        "Name": "y"
      }
    } 
  ]
}
```

We can discuss further on gitter, if you are available on Monday?

**Pull request merged**
